keptn/examples

onboarding-carts/values_carts.yaml

When using LoadBalancer we have the risk of not receiving an external IP for the service (which we don't need anyway because we expose it via Istio VirtualServices), and the helm upgrade --wait command will time out

#737 use ClusterIP instead of LoadBalancer for service type

---

onboarding-carts/values_carts.yaml

When using LoadBalancer we have the risk of not receiving an external IP for the service (which we don't need anyway because we expose it via Istio VirtualServices), and the helm upgrade --wait command will time out

#737 use ClusterIP instead of LoadBalancer

---

onboarding-carts/carts/templates/deployment.yaml
onboarding-carts/carts/values.yaml

- Increased cpu limits to reduce restart loops as the service took 90 seconds to start
- Change image version/tag to 0.10.1

#1086 increase cpu limits

---

unleash-server/unleash-db/templates/db-deployment.yaml

If we edit the deployment (e.g., by sending a new-artifact with deployment-strategy=direct-deployment) Kubernetes will create a new pod and wait for the new pod to be ready before the old pod will be removed.
This behaviour is not desireable for postgres with a Persistent Volume Claim (PVC), as acquiring the PVC is blocking and the new pod will never come up.
This change fixes this behaviour. We also have the very same setting in carts-db:
https://github.com/keptn/examples/blob/a45849655fd76325fe2e8101a7456f271452b5da/onboarding-carts/carts-db/templates/carts-db-deployment.yaml#L22-L23

Added strategy type recreate for database

---

unleash-server/unleash-db/templates/db-deployment.yaml

The StorageClassName=standard definition is not needed, it might fail in K8s versions when finding the default class leading to unbound PVC and to failed PoD deployment.

StorageClassName=standard definition is not needed

---

onboarding-carts/slo-quality-gates.yaml
onboarding-carts/slo-self-healing.yaml

Added the default values `key_sli: false` and `number_of_comparison_results: 1` to the SLO configs.

#1495 Add default values to SLO config

---

onboarding-carts/carts-db/templates/carts-db-deployment.yaml
onboarding-carts/carts/templates/deployment.yaml

This implements #91 and adds some recommended K8s labels to the deployment manifest.
For instance, the carts deployment (and the pod) now has the following labels:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
name: carts
namespace: sockshop-production
spec:
replicas: 1
selector:
matchLabels:
app: carts
strategy:
rollingUpdate:
maxSurge: 25%
maxUnavailable: 0
type: RollingUpdate
template:
metadata:
creationTimestamp: null
labels:
app: carts
app.kubernetes.io/component: api
app.kubernetes.io/instance: carts-canary
app.kubernetes.io/managed-by: Keptn
app.kubernetes.io/name: carts
app.kubernetes.io/part-of: sockshop
spec:
containers:
- env:
- name: DT_CUSTOM_PROP
value: keptn_project=sockshop keptn_service=carts keptn_stage=production
keptn_deployment=canary
image: …
```

Added kubernetes recommended labels to carts and carts-db deployment manifest

---

load-generation/cartsloadgen/deploy/cartsloadgen-base.yaml
load-generation/cartsloadgen/deploy/cartsloadgen-fast.yaml
load-generation/cartsloadgen/deploy/cartsloadgen-faulty.yaml
onboarding-carts/argo/carts/templates/carts-db-deployment.yaml
onboarding-carts/carts-db/templates/carts-db-deployment.yaml
onboarding-carts/manifests/manifest-carts-db.yaml
onboarding-carts/manifests/manifest-carts.yaml
unleash-server/unleash-db/templates/db-deployment.yaml
unleash-server/unleash/templates/deployment.yaml

Fixes #101 
This PR updates to Kubernetes Manifests from apiVersion v1beta to `apps/v1`.
This ensures our examples are compatible with newer K8s versions.

#101 Update K8s manifest apiVersion to apps/v1 to be compatible with K8s 1.16+

---

unleash-server/README.md

Changed the configmap from keptn-domain to ingress-config because keptn-domain is no longer available in Keptn version 0.7.

Changed configmap from keptn-domain to ingress-config for Keptn 0.7 compatibility

---

load-generation/cartsloadgen/deploy/cartsloadgen-prod.yaml

In order to have the "unleash self healing use case" to not trigger problems for each stage (dev, staging, production) we only generate traffic for the production stage

add loadgen for prod only

---

onboarding-carts/sli-config-prometheus-bg.yaml
onboarding-carts/sli-config-prometheus.yaml

The `-canary` filter was missing and thus the metrics for the wrong version got pulled.
needed for: https://github.com/keptn/tutorials/issues/91 
Signed-off-by: jetzlstorfer <juergen.etzlstorfer@dynatrace.com>

fix missing canary tag for bluegreen deployment SLI

---

istio-configuration/configure-istio.sh

Changed config map command to remove kubectl deprecated warning.
The ```--dry-run``` parameter is going to be deprecated and should be replaced with ```--dry-run=client```.

Remove kubectl deprecated warning

---

istio-configuration/configure-istio.sh

Changed config map command to remove kubectl deprecated warning.
The ```--dry-run``` parameter is going to be deprecated and should be replaced with ```--dry-run=client```.

Remove kubectl deprecated warning on master

---

onboarding-carts/shipyard.yaml

part of: https://github.com/keptn/keptn/issues/3029
* changed shipyard to use "triggeredOn" intead of "triggers" 
* use separate rollback sequence 
* renamed sequences
Signed-off-by: warber <bernd.warmuth@dynatrace.com>

Adapt carts example to correct trigger names and rollback structure

---

istio-configuration/configure-istio.sh

Fixes #157 
This PR improves log output of the configure-istio.sh script.

#157 Improve output of configure-istio.sh script

---

istio-configuration/configure-istio.sh

The current API version used to create the Istio ingress manifest is being deprecated and therefore needs to be replaced to work with newer versions of kubectl.

Update istio ingress API version

---

onboarding-carts/sli-config-dynatrace-no-deployment-tag.yaml
onboarding-carts/sli-config-dynatrace.yaml

This PR switches the Dynatrace SLI definitions to use a dimension key in merge transformations and entity selectors rather than scopes.
Closes #188 
Closes #123 
Signed-off-by: Arthur Pitman <arthur.pitman@dynatrace.com>

Update Dynatrace SLI definitions

---

.versionrc.json

* removes the `v` version tag prefix from the automated release config to follow the scheme of previous releases

fix: Remove v prefix in version tags for automated releases

---

quickstart/demo/slo.yaml

The SLO file for the quickstart example and the podtatohead version used are out of sync. The [SLO file](https://github.com/keptn/examples/blob/master/quickstart/demo/slo.yaml#L12) checks for an HTTP response time of 1 second, but the [actual delay](https://github.com/jetzlstorfer/podtato-head/blob/main/podtato-server/podtatoserver.go#L83) of the used podatohead is only 200ms and does therefore not trigger the SLO criteria.
The PR fixes this problem by reducing the SLO time to 200ms.
Run the [quickstart guide](https://keptn.sh/docs/quickstart/) using the new SLO file.

fix: change SLO values for new podtatohead image

---

CODEOWNERS

- Removes me @christian-kreuzberger-dtx from CodeOwners,
- Removes Daniel Khan from CodeOwners,
- Adds @thisthat to CodeOwners.
Fixes #209

chore: Remove myself from codeowners, add thisthat (#209)

---

quickstart/automated-operations.sh
quickstart/demo/jmeter/jmeter.conf.yaml
quickstart/demo/prometheus/sli.yaml
quickstart/demo/slo.yaml
quickstart/multistage-delivery.sh

**changes the quickstart guide using podtato-head as follows**
* Upgrade to prometheus-service 0.7.1
* Fix a typo in the `source` field when simulating an alert using prometheus
* Use vanilla (original) podtato-head images
* Change jmeter config in order to decrease the time needed for the performance test executed using JMeter
* Change SLI/SLO defnition to fit the vanilla (original) podtato-head-images
Fixes #213

fix: Use vanilla podtato-head images for quickstart

---

quickstart/demo/slo.yaml

Fixes https://github.com/keptn/keptn.github.io/issues/984 in the quickstart guide
- Looks like there is a regression in the Prometheus service which impacts proper config generation if the SLI check contains spaces. This PR fixes it. https://github.com/keptn/keptn.github.io/issues/984
- https://github.com/keptn/keptn.github.io/issues/984

fix: Update Quickstart SLI config to produce proper Configuration YAML in the Prometheus Service

---

onboarding-carts/argo/carts/values.yaml
onboarding-carts/carts/values.yaml
onboarding-carts/manifests/manifest-carts.yaml

Due to a new release of the carts service, an update of the docs for the newest Keptn version had to be done.
Signed-off-by: Johannes <johannes.braeuer@dynatrace.com>

feat: Change from carts:0.11 to carts:0.13

---

quickstart/demo/prometheus/sli.yaml

- Fixes a problem with quickstart prometheus sli.yaml, where failing_requests could not be properly used for creating an alert

fix: quickstart prometheus failing_requests SLI was malformated

---

quickstart/multistage-delivery.sh

- udpates quickstart to the newest version of prometheus-service 0.7.2
- removes the secret creation for prometheus (it's not needed)

feat: upgrade to prometheus-service 0.7.2

---

quickstart/expose-keptn.sh
quickstart/multistage-delivery.sh

Currently, the open command used in the quickstart tutorial scripts does not work on Linux machines, as described in issue #207. Now we check which OS the script is being executed on and change the command accordingly.
Fixes #207

fix: Open command on linux

---

quickstart/multistage-delivery.sh

Currently, when the `multistage-delivery.sh` script of the quickstarter example is run multiple times, it fails since the `examples` repository already exists.
```
fatal: destination path 'examples' already exists and is not an empty directory.
```
Now the existence of the directory gets checked before cloning the repository to remove the possibility of this error.
[Keptn.sh issue](https://github.com/keptn/keptn.github.io/issues/860)

fix: Check if example directory already exists

---

quickstart/expose-keptn.sh

- Fixes bug inside `expose-keptn.sh` file that retries the opening of the Keptn bridge even though it was already open. This is due to a missing break statement.
-  Also fixes the some minor formatting issues (wrong spacing)
Run `curl -SL https://raw.githubusercontent.com/keptn/examples/master/quickstart/expose-keptn.sh | bash`

fix: Fixed retrying bug even if opening bridge is successful

---

istio-configuration/configure-istio.sh
quickstart/expose-keptn.sh
quickstart/multistage-delivery.sh

Signed-off-by: odubajDT <ondrej.dubaj@dynatrace.com>
Fixes https://github.com/keptn/keptn/issues/4407

fix: Deprecate Kubernetes versions under v1.19 + support Openshift 3.11

---

istio-configuration/configure-istio.sh
quickstart/expose-keptn.sh
quickstart/multistage-delivery.sh

Removes the need to have jq installed to run [istio-configuration/configure-istio.sh](https://github.com/keptn/examples/blob/4e16dc19a26b4f17822f9c85509e084b1e974c35/istio-configuration/configure-istio.sh), [quickstart/expose-keptn.sh](https://github.com/keptn/examples/blob/4e16dc19a26b4f17822f9c85509e084b1e974c35/quickstart/expose-keptn.sh) and [quickstart/multistage-delivery.sh](https://github.com/keptn/examples/blob/4e16dc19a26b4f17822f9c85509e084b1e974c35/quickstart/multistage-delivery.sh) as described in #223
Fixes #223

fix: removed jq dependency

---

onboarding-carts/dynatrace/dynatrace.conf.yaml

Signed-off-by: Arthur Pitman <arthur.pitman@dynatrace.com>
- Adds a default `dynatrace/dynatrace.conf.yaml` file, intended for use in the Keptn Full Tour on Dynatrace tutorial.
- Due to the changes introduced in https://github.com/keptn-contrib/dynatrace-service/pull/612, a  `dynatrace/dynatrace.conf.yaml` file is always required to use the dynatrace-service.

feat: Add default `dynatrace/dynatrace.conf.yaml`

---

quickstart/automated-operations.sh
quickstart/demo/job/job-executor.yaml

This PR will fix the Quickstart tutorial as mentioned in #227 
1. The auto remediation use case cannot be run without the multi-stage delivery because `podtatohead-production` won't exist. Docs should be updated to mention that the flow is: `Keptn hello world > multi stage delivery > auto remediation`
```
{
"data": {
"message": "Job job-executor-service-job-6e3b00dc-5586-45d7-9ce6-635c-1 failed: job job-executor-service-job-6e3b00dc-5586-45d7-9ce6-635c-1 failed. Reason: BackoffLimitExceeded, Message: Job has reached the specified backoff limit\n\nLogs: \nThe connection to the server localhost:8080 was refused - did you specify the right host or port?\n",
"project": "podtatohead",
"result": "fail",
"service": "helloservice",
"stage": "production",
"status": "errored"
},
"id": …
```

Fix Quickstart

---

onboarding-carts/sli-config-prometheus-bg.yaml
onboarding-carts/sli-config-prometheus-selfhealing.yaml
onboarding-carts/sli-config-prometheus.yaml

- Updates prometheus-services SLI config files for the onboarding-carts example
**Reason**: With [Prometheus-Service 0.7.3](https://github.com/keptn-contrib/prometheus-service/releases/tag/0.7.3) we are finally able to use `$DEPLOYMENT` in the SLI config, and no longer need multiple SLI files.
**IMPORTANT NOTE**: This also needs to be reflected in keptn/tutorials. Once this PR is merged and released (e.g., keptn/exampels@0.14.0), we need to update tutorials, e.g.:
```
keptn add-resource --project=sockshop --stage=staging --service=carts --resource=sli-config-prometheus-bg.yaml --resourceUri=prometheus/sli.yaml 
```
changes to
```
keptn add-resource --project=sockshop --stage=staging --service=carts --resource=sli-config-prometheus.yaml --resourceUri=prometheus/sli.yaml 
```

feat: Use latest prometheus-service SLI placeholders

---

quickstart/multistage-delivery.sh

As per https://cloud-native.slack.com/archives/C017GAX90GM/p1652709824176979 we were notified that the quickstart example does not work anymore with prometheus-service crashing.
This is due to the fact that the quickstart uses the latest Keptn version (e.g., 0.15.0), but prometheus-service 0.7.2 is not comptabiel with that (breaking change introduced by Keptn 0.14.x).
With this PR, I'm setting the [prometheus-service version to 0.8.0](https://github.com/keptn-contrib/prometheus-service/releases/tag/0.8.0), which addresses this breaking change.

fix: Update quickstart example to use prometheus-service 0.8.0
