onboarding-carts/slo_quality-gates.yaml
onboarding-carts/slo_self-healing_prometheus.yaml

As spec is released at version 0.1.0 we should change the example slo files accordingly

#1059 change spec version to 0.1.0

---

onboarding-carts/shipyard_quality_gates.yaml
onboarding-carts/slo_quality-gates.yaml

Provide a shipyard with a single stage for the quality gates use case.

#1202 Provide a single stage shipyard

---

README.md
onboarding-carts/remediation.yaml
onboarding-carts/remediation_feature_toggle.yaml
unleash-server/README.md
unleash-server/shipyard.yaml
unleash-server/unleash-db/Chart.yaml
unleash-server/unleash-db/templates/db-deployment.yaml
unleash-server/unleash-db/templates/db-service.yaml
unleash-server/unleash-db/values.yaml
unleash-server/unleash/Chart.yaml
unleash-server/unleash/templates/deployment.yaml
unleash-server/unleash/templates/service.yaml
unleash-server/unleash/values.yaml

Updated the remediaton file with instructions to toggle feature flags.
Added Helm charts for the onboarding of Unleash as the feature toggle framework server.

#1104 Files for feature toggle example

---

onboarding-carts/carts/templates/deployment.yaml

Unleash URL needs to be configured as an environment variable

#1104 added unelash server url to environment variable

---

onboarding-carts/sli-config-dynatrace.yaml

Related issue https://github.com/keptn-contrib/dynatrace-sli-service/issues/30

Dynatrace SLIs should use throughput.sum rather than throughput.count

---

onboarding-carts/sli-config-dynatrace-no-deployment-tag.yaml

This custom SLI config does **not** contain the DEPLOYMENT tag as a query parameter for scoping. The reason is that there is no need for this tag when working through the quality gates only use case.

#447 Add custom SLI config for Quality Gates only UC

---

onboarding-carts/manifests/manifest-carts-db.yaml
onboarding-carts/manifests/manifest-carts.yaml

provide plain manifests for use cases with non-keptn deployments

provide manifests for other use cases

---

onboarding-carts/manifests/manifest-carts-db.yaml
onboarding-carts/manifests/manifest-carts.yaml

Added selector to the carts-db-deployment

Add selector to deployments

---

dynatrace-oneagent/deploy-dynatrace-oneagent.sh
istio-configuration/configure-istio.sh

- Added scripts for automating tasks for `Full tour on Dynatrace` tutorial

Examples for Keptn tutorials 

---

onboarding-carts/carts-db/templates/carts-db-deployment.yaml

fixes #144
Signed-off-by: warber <bernd.warmuth@dynatrace.com>

increased storage of mongo db from 100Mi to 1Gi

---

onboarding-carts/shipyard-argo.yaml
onboarding-carts/shipyard-quality-gates.yaml
onboarding-carts/shipyard.yaml
unleash-server/shipyard.yaml

#143 Updated shipyard files

---

onboarding-carts/sli-config-prometheus-selfhealing.yaml

Fixed sli config for prometheus

---

README.md
releasenotes/releasenotes_V0.8.0-alpha.md

Signed-off-by: Christian Kreuzberger <christian.kreuzberger@dynatrace.com>

0.8.0-alpha release with semver

---

unleash-server/shipyard.yaml

Renamed 'artifact-delivery' sequence to 'delivery'

---

README.md
releasenotes/releasenotes_V0.8.0.md

Prepare release-0.8.0

---

onboarding-carts/slo-quality-gates.yaml
onboarding-carts/slo-self-healing.yaml

Signed-off-by: Johannes <johannes.braeuer@dynatrace.com>

Update of SLO files for carts to show display name

---

README.md
releasenotes/releasenotes_V0.8.2.md
releasenotes/releasenotes_develop.md

Preparing release 0.8.2 according to https://github.com/keptn/keptn/issues/3746

prepare release 0.8.2

---

README.md
releasenotes/releasenotes_V0.8.2.md
releasenotes/releasenotes_develop.md

Release 0.8.2 of keptn/examples as defined by https://github.com/keptn/keptn/issues/3746

Release 0.8.2

---

README.md
releasenotes/releasenotes_V0.8.3.md
releasenotes/releasenotes_develop.md

Prepare release 0.8.3

---

onboarding-carts/shipyard.yaml

During testing I noticed that we need to raise the wait time to 15 minutes

Increase wait time for tutorial

---

README.md
releasenotes/releasenotes_V0.8.4.md

Prepare release 0.8.4

---

istio-configuration/configure-istio.sh

fixes #177 
Signed-off-by: warber <bernd.warmuth@dynatrace.com>

updated ingress manifest in configure-istio.sh

---

istio-configuration/configure-istio.sh

Fixes #177 on release-0.8.4 branch

Hotfix: fix istio configuration

---

istio-configuration/configure-istio.sh
releasenotes/releasenotes_V0.8.4.md

Hotfix: reverted changes to istio configuration

---

releasenotes/releasenotes_develop.md

empty release notes

---

quickstart/demo/helm/hardening_endpoints.yaml
quickstart/demo/helm/production_endpoints.yaml
quickstart/multistage-delivery.sh

Adds the right endpoints to all stages of the podtatohead project.
#201

fix: Added endpoints for all stages

---

quickstart/demo/slo.yaml

fix: SLO variable typo

---

quickstart/multistage-delivery.sh

Signed-off-by: Johannes <johannes.braeuer@dynatrace.com>

fix: Set new release version of prometheus-service

---

CODEOWNERS

chore: Add @oleg-nenashev to codeowners for all repository locations
